"""empty message

Revision ID: cd6063a2dbd1
Revises: 4a24fad636f7
Create Date: 2020-02-28 14:57:58.433041

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd6063a2dbd1'
down_revision = '4a24fad636f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ad_ibfk_1', 'ad', type_='foreignkey')
    op.drop_column('ad', 'user_id1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad', sa.Column('user_id1', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('ad_ibfk_1', 'ad', 'user', ['user_id1'], ['user_id'])
    # ### end Alembic commands ###
