"""empty message

Revision ID: dd6f0d40e02e
Revises: cd6063a2dbd1
Create Date: 2020-02-28 16:44:01.410407

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dd6f0d40e02e'
down_revision = 'cd6063a2dbd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'city',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('user', 'document_id',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('user', 'ip_address',
               existing_type=mysql.VARCHAR(length=24),
               nullable=True)
    op.alter_column('user', 'last_name',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('user', 'last_name2',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('user', 'phone_number',
               existing_type=mysql.VARCHAR(length=11),
               nullable=True)
    op.alter_column('user', 'ping',
               existing_type=mysql.VARCHAR(length=4),
               nullable=True)
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('user', 'verified',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'verified',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('user', 'ping',
               existing_type=mysql.VARCHAR(length=4),
               nullable=False)
    op.alter_column('user', 'phone_number',
               existing_type=mysql.VARCHAR(length=11),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('user', 'last_name2',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('user', 'last_name',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('user', 'ip_address',
               existing_type=mysql.VARCHAR(length=24),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('user', 'document_id',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('user', 'city',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    # ### end Alembic commands ###
